# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baf1a2a7844fb1aa782c6578a26f7f7c3005e4aa2030ef8ada1fe22cf3d41b28a2c68c823ef6f8fc51409f346926a290b27a6b198208e5cda248b1b102a67697

test:
  secret_key_base: e8fe093c9935e6fbe783013264aca1f6fc7cfe9fa24969875bc16bca7324c89ef6bc0ebcde45488c4a7e4b82fd174c6f20dcb8dc89c9204d22a5bd35eea24155

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
